locals = {
  bastion_autoscaling_group_ids     = ["${aws_autoscaling_group.bastions-farrukhcluster-com.id}"]
  bastion_security_group_ids        = ["${aws_security_group.bastion-farrukhcluster-com.id}"]
  bastions_role_arn                 = "${aws_iam_role.bastions-farrukhcluster-com.arn}"
  bastions_role_name                = "${aws_iam_role.bastions-farrukhcluster-com.name}"
  cluster_name                      = "farrukhcluster.com"
  master_autoscaling_group_ids      = ["${aws_autoscaling_group.master-eu-west-1a-masters-farrukhcluster-com.id}", "${aws_autoscaling_group.master-eu-west-1b-masters-farrukhcluster-com.id}", "${aws_autoscaling_group.master-eu-west-1c-masters-farrukhcluster-com.id}"]
  master_security_group_ids         = ["${aws_security_group.masters-farrukhcluster-com.id}"]
  masters_role_arn                  = "${aws_iam_role.masters-farrukhcluster-com.arn}"
  masters_role_name                 = "${aws_iam_role.masters-farrukhcluster-com.name}"
  node_autoscaling_group_ids        = ["${aws_autoscaling_group.nodes-farrukhcluster-com.id}"]
  node_security_group_ids           = ["${aws_security_group.nodes-farrukhcluster-com.id}"]
  node_subnet_ids                   = ["${aws_subnet.eu-west-1a-farrukhcluster-com.id}", "${aws_subnet.eu-west-1b-farrukhcluster-com.id}", "${aws_subnet.eu-west-1c-farrukhcluster-com.id}"]
  nodes_role_arn                    = "${aws_iam_role.nodes-farrukhcluster-com.arn}"
  nodes_role_name                   = "${aws_iam_role.nodes-farrukhcluster-com.name}"
  region                            = "eu-west-1"
  route_table_private-eu-west-1a_id = "${aws_route_table.private-eu-west-1a-farrukhcluster-com.id}"
  route_table_private-eu-west-1b_id = "${aws_route_table.private-eu-west-1b-farrukhcluster-com.id}"
  route_table_private-eu-west-1c_id = "${aws_route_table.private-eu-west-1c-farrukhcluster-com.id}"
  route_table_public_id             = "${aws_route_table.farrukhcluster-com.id}"
  subnet_eu-west-1a_id              = "${aws_subnet.eu-west-1a-farrukhcluster-com.id}"
  subnet_eu-west-1b_id              = "${aws_subnet.eu-west-1b-farrukhcluster-com.id}"
  subnet_eu-west-1c_id              = "${aws_subnet.eu-west-1c-farrukhcluster-com.id}"
  subnet_utility-eu-west-1a_id      = "${aws_subnet.utility-eu-west-1a-farrukhcluster-com.id}"
  subnet_utility-eu-west-1b_id      = "${aws_subnet.utility-eu-west-1b-farrukhcluster-com.id}"
  subnet_utility-eu-west-1c_id      = "${aws_subnet.utility-eu-west-1c-farrukhcluster-com.id}"
  vpc_cidr_block                    = "${aws_vpc.farrukhcluster-com.cidr_block}"
  vpc_id                            = "${aws_vpc.farrukhcluster-com.id}"
}